export const postItem = [
    {
        "id": 1,
        "title": "Cần bán căn hộ Vinhomes Grand Park - phân khu Rainbow toà S3.05",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hà Nội",
        "distric": "Đống Đa",
        "ward": "Trung Liệt",
        "address": "175 Tây Sơn, Trung Liệt, Đống Đa, Hà Nội",
        "sqm": 50,
        "price": 1900000000,
        "describe": "Mình chủ nhà, cần bán căn hộ tại Đại đô thị Vinhomes Grand Park Quận 9. Vị trí Tòa nhà phân khu The Rainbow. Tòa S3.05 diện tích 49m², 1PN. View sông Tắc, hướng Đông Nam. Giá rẻ hơn thị trường, tiện mua ở hoặc đầu tư. Khách mua có thể nhận nhà công chứng vào ở ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 2,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 1,
        "date": "01/01/2022"
    },
    {
        "id": 3,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 4,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 5,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 1,
        "date": "01/01/2022"
    },
    {
        "id": 6,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 1,
        "date": "01/01/2022"
    },
    {
        "id": 7,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 8,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 9,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 10,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 11,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 12,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 3,
        "date": "01/01/2022"
    },
    {
        "id": 13,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 14,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 1,
        "date": "01/01/2022"
    },
    {
        "id": 15,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 1,
        "date": "01/01/2022"
    },
    {
        "id": 16,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 1,
        "date": "01/01/2022"
    },
    {
        "id": 17,
        "title": "Cần bán căn hộ Vinhomes Grand Park - phân khu Rainbow toà S3.05",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hà Nội",
        "distric": "Đống Đa",
        "ward": "Trung Liệt",
        "address": "175 Tây Sơn, Trung Liệt, Đống Đa, Hà Nội",
        "sqm": 50,
        "price": 1900000000,
        "describe": "Mình chủ nhà, cần bán căn hộ tại Đại đô thị Vinhomes Grand Park Quận 9. Vị trí Tòa nhà phân khu The Rainbow. Tòa S3.05 diện tích 49m², 1PN. View sông Tắc, hướng Đông Nam. Giá rẻ hơn thị trường, tiện mua ở hoặc đầu tư. Khách mua có thể nhận nhà công chứng vào ở ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 18,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 3,
        "date": "01/01/2022"
    },
    {
        "id": 19,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 3,
        "date": "01/01/2022"
    },
    {
        "id": 20,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 21,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 22,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 23,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 24,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 25,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 26,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 27,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 3,
        "date": "01/01/2022"
    },
    {
        "id": 28,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 29,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 3,
        "date": "01/01/2022"
    },
    {
        "id": 30,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 4,
        "date": "01/01/2022"
    },
    {
        "id": 31,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 2,
        "date": "01/01/2022"
    },
    {
        "id": 32,
        "title": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2",
        "category": "Bán",
        "type": "Căn hộ",
        "city": "TP.Hồ Chí Minh",
        "distric": "Quận 2",
        "ward": "Bình Khánh",
        "address": "New City Thủ Thiêm, Phường Bình Khánh, Quận 2, TP.Hồ Chí Minh",
        "sqm": 70,
        "price": 5200000000,
        "describe": "BÁN CĂN HỘ 2PN2WC NEW CITY PHƯỜNG BÌNH KHÁNH QUẬN 2. Diện tích thông thủy: 69.74 m2. Diện tích tim tường: 74.73 m2. Cửa chính hướng: Đông Nam. View ban công hướng: Tây Bắc. Bố trí: 2PN2WC, không gian bếp, phòng khách. Tặng nội thất cao cấp như hình. Nhà trong khu an ninh yên tĩnh, dễ cho thuê giá cao. New City Thủ Thiêm sở hữu một vị trí vô cùng đắc địa, nằm ngay mặt tiền đường Mai Chí Thọ, đối diện với 2 khu đô thị lớn là khu đô thị Sala và The Sun Avenue. Không chỉ mang tới không gian thoáng đãng, một không gian sống xanh mà còn mang tới cho cư dân rất nhiều tiện ích đa dạng nằm trong cũng như nằm xung quanh khu căn hộ chung cư. Tiện ích nội khu: hồ bơi, phố đi bộ, công viên cây xanh, trường học từ cấp mẫu giáo tới THPT, bệnh viện, sát TT Q1, TT Q2, hưởng trọn tiện ích của khu vực nơi đây. HĐMB chính chủ - Giao dịch ngay.",
        "image": "",
        "userId": 3,
        "date": "01/01/2022"
    }
]

export const userItem = [
    {
        "userId": 1,
        "avatar": "",
        "name": "Phạm Ánh Dương",
        "email": "duong@gmail.com",
        "phone": "0987654321",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "admin"
    },
    {
        "userId": 2,
        "avatar": "",
        "name": "Nguyễn Văn A",
        "email": "a@gmail.com",
        "phone": "0123456789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 3,
        "avatar": "",
        "name": "Đinh Thị B",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Chặn",
        "role": "user"
    },
    {
        "userId": 4,
        "avatar": "",
        "name": "Đinh Thị C",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 5,
        "avatar": "",
        "name": "Đinh Thị D",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 6,
        "avatar": "",
        "name": "Đinh Thị E",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "admin"
    },
    {
        "userId": 7,
        "avatar": "",
        "name": "Đinh Thị F",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Chặn",
        "role": "user"
    },
    {
        "userId": 8,
        "avatar": "",
        "name": "Đinh Thị G",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "admin"
    },
    {
        "userId": 9,
        "avatar": "",
        "name": "Đinh Thị H",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 10,
        "avatar": "",
        "name": "Đinh Thị I",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 11,
        "avatar": "",
        "name": "Đinh Thị I",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 12,
        "avatar": "",
        "name": "Đinh Thị I",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 13,
        "avatar": "",
        "name": "Đinh Thị I",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    },
    {
        "userId": 14,
        "avatar": "",
        "name": "Đinh Thị I",
        "email": "b@gmail.com",
        "phone": "0543216789",
        "facebook": "",
        "other": "",
        "address": "",
        "status": "Bình thường",
        "role": "user"
    }
]